{-
A string is simply an ordered collection of symbols selected from some alphabet and formed into a word; 
the length of a string is the number of symbols that it contains.

An example of an RNA string (whose alphabet contains A, C, G, and U) is AUGCUUCAGAAAGGUCUUACG.

Given: An RNA string s of length at most 1000 nt.

Return: Four integers corresponding to the number of times that the symbols A, C, G, and U occur in s.

Sample Dataset
AGCUUUUCAUUCUGACUGCAACGGGCAAUAUGUCUCUGUGUGGAUUAAAAAAAGAGUGUCUGAUAGCAGC
Sample Output
20 12 17 21
-}

input = "UCUUGCCAACUAGCUGUCCUCUCAUGGGCCGGUAAAUAAGCUAGGCCCGGUACUUCUGGCCUACGACCUAAAUGUAGUGAACCCGAGAUAUUGCCACUGGGUAUUAAGAUUACCACAAUGUCGCCCUUUGUCGUUUUUCGUGAAAUCCUUCCCAGCUACCAUCGACAACAGGUCAAGGGCUGUCUUUGAUACAUAUUCCCCCGCGACCAUGUGACAACUGCUUAUGGGCCUUCACAUGGACAUCUAGUUUCCAAGCGAAUCGUGAGUAGAUUGGUACUGAGUGCUGUAUCAGAGCCGAAUUACUCGACAUUUAAGACAAUUAAACCGCAAUGAUACUUAAAGGUGUCACCUAGCUGCACACACGAUCGUGGUCUUAAUCGUACAAUACAACAGGACCCUAUUUUAAAGCUCCACGGUCUUCAUUUUGCGCUAGCCAGAGGAGGACGAGAAGCCAUAUUAAAUGAUGCGCGUAUUCUUAUGGAUAUUUUAACCAUGAACUUACAUUGAGUGGGAAAUUCACUAGAUAAUCCGCAGUGCUUGCUCCGAUUUGCUUCUCCGUUUCCUGGCAUUCCACGAGCGUGUCCAAUAUCAUUCCCCGAUAGCUGCCCGGCAUAGAAGUCCAGCGAACAGUUUUCGCAACCUACAUUCAGCAAUUGAUAUGACUUGUGGUGCGUUUAUUGGUGGUGGACGACUAUUCGGAUCUGACGCAAACGGUUGUCGGCUCUCUAUGCAUCGCUCGUGUAUUUCGCAAUGGUGUUACCCUCAUAGGCUGCGGAUACGCCGAGCCUACCAAAUACCCGCGGAGUAGAUCGUGCUCUCUGGUUUCCAAAGCCGUUUCGCUCCGGUCCACAGCUUCUUCUCCUACGGGUUUGUCGUAGGUGGGUCGGGCAUAGGACCCGGUGCCUUCCUUACGGGUAAG"

nucleotides = ['A', 'C', 'G', 'U']

counts = map (\x -> length $ filter (== x) input) nucleotides

main = print $ unwords $ map show counts